# Generated by Django 5.0.6 on 2024-10-30 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_messageforadmin_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWithAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('messages', models.ManyToManyField(related_name='chats_with_admin', to='users.messageforadmin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_with_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin chat',
                'verbose_name_plural': 'Admin chatlar',
            },
        ),
    ]
