# Generated by Django 5.0.6 on 2024-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ball',
            field=models.FloatField(default=0),
        ),
    ]
