# Generated by Django 5.0.6 on 2024-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_quiz_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtm',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
