# Generated by Django 5.0.6 on 2024-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmresult',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
