# Generated by Django 5.0.6 on 2024-10-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0009_dtmresult_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmresult',
            name='chosen_variant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dtmresult',
            name='true_variant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
