# Generated by Django 5.0.6 on 2024-10-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0012_alter_dtm_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtm',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
