# Generated by Django 5.0.6 on 2024-10-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0013_alter_dtm_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='quizes/docx_files'),
        ),
    ]
