# Generated by Django 5.0.6 on 2024-10-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0014_question_docx_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='docx_file',
        ),
        migrations.AddField(
            model_name='quiz',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='quizes/docx_files'),
        ),
    ]
