# Generated by Django 5.0.6 on 2024-10-16 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0016_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='blog_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='quizes.dtm'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='quizes.quiz'),
        ),
    ]
