# Generated by Django 5.0.6 on 2024-10-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0017_feedback_blog_test_alter_feedback_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizes.variant'),
        ),
    ]
