# Generated by Django 5.0.6 on 2024-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0019_feedback_send_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='with_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
